use_frameworks!

platform :ios, '12.0'

target 'CircomWitnesscalc_Example' do
  use_frameworks! :linkage => :dynamic

  pod 'CircomWitnesscalc', :path => '../'
  pod 'rapidsnark', '0.0.1-alpha.5'
end
