use_frameworks!

platform :ios, '12.0'

target 'WitnessGraph_Example' do
  use_frameworks! :linkage => :dynamic

  pod 'WitnessGraph', :path => '../'
  pod 'rapidsnark', :path => '../../rapidsnark-ios'
end
